# Generated by Django 4.0.5 on 2022-06-16 03:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_district_district_reach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_things',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
