# Generated by Django 4.0.5 on 2022-06-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hotel_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('room', models.IntegerField()),
            ],
        ),
    ]
